// Code generated by gen-dao. DO NOT EDIT.
package features

import (
	"context"
	"fmt"
	"math"
	"strings"
	"time"
	"github.com/go-gorp/gorp/v3"
)

var (
	_ = fmt.Sprintf
	_ = strings.Join
	_ = time.Now
	_ = math.Max
)

func Execute一覧SQLBOM(ctx context.Context, dbmap *gorp.DbMap, input 一覧InputBOM) (ListResultBOM, error) {
	size := input.Size
	if size != 20 && size != 50 && size != 100 {
		size = 20
	}

	where := "WHERE 1=1"
	args := []any{}
	if input.Search != "" {
		args = append(args, "%"+input.Search+"%")
		idx := len(args)
		where += fmt.Sprintf(` AND ("コード" ILIKE $%d OR "名称" ILIKE $%d)`, idx, idx)
	}

	var total int
	if err := dbmap.SelectOne(&total, `SELECT COUNT(*) FROM "BOM" `+where, args...); err != nil {
		return ListResultBOM{}, err
	}

	totalPages := int(math.Max(1, math.Ceil(float64(total)/float64(size))))
	page := input.Page
	if page < 1 { page = 1 }
	if page > totalPages { page = totalPages }

	offset := len(args)
	rows, err := dbmap.Db.QueryContext(ctx,
		fmt.Sprintf(`SELECT id, "コード", "版", "名称", created_at, updated_at FROM "BOM" %s ORDER BY id DESC LIMIT $%d OFFSET $%d`, where, offset+1, offset+2),
		append(args, size, (page-1)*size)...)
	if err != nil {
		return ListResultBOM{}, err
	}
	defer rows.Close()

	var records []ResponseBOM
	for rows.Next() {
		var r RowBOM
		if err := rows.Scan(&r.Id, &r.コード, &r.版, &r.名称, &r.CreatedAt, &r.UpdatedAt); err != nil {
			return ListResultBOM{}, err
		}
		records = append(records, ResponseBOM{RowBOM: r})
	}
	if records == nil { records = []ResponseBOM{} }

	return ListResultBOM{Records: records, CurrentPage: page, TotalPages: totalPages, PageSize: size}, nil
}

func Execute登録SQLBOM(ctx context.Context, dbmap *gorp.DbMap, input 作成InputBOMWithLines) (ResponseBOM, error) {
	now := time.Now()
	tx, err := dbmap.Begin()
	if err != nil {
		return ResponseBOM{}, err
	}
	defer tx.Rollback()

	r := RowBOM{
		コード: input.コード,
		版: input.版,
		名称: input.名称,
		CreatedAt: now,
		UpdatedAt: now,
	}
	if err := tx.Insert(&r); err != nil {
		return ResponseBOM{}, err
	}

	for _, l := range input.LinesBOM明細 {
		line := BOM明細{
			BOMID: r.Id,
			区分: l.区分,
			品目ID: l.品目ID,
			数量: l.数量,
			単位: l.単位,
			参照BOMコード: toNullString(l.参照BOMコード),
			参照BOM版: toNullString(l.参照BOM版),
			CreatedAt: now,
			UpdatedAt: now,
		}
		if err := tx.Insert(&line); err != nil {
			return ResponseBOM{}, err
		}
	}

	if err := tx.Commit(); err != nil {
		return ResponseBOM{}, err
	}
	return ResponseBOM{RowBOM: r}, nil
}

func Execute更新SQLBOM(ctx context.Context, dbmap *gorp.DbMap, input 更新InputBOMWithLines) (ResponseBOM, error) {
	now := time.Now()
	tx, err := dbmap.Begin()
	if err != nil {
		return ResponseBOM{}, err
	}
	defer tx.Rollback()

	obj, err := tx.Get(RowBOM{}, input.ID)
	if err != nil {
		return ResponseBOM{}, err
	}
	if obj == nil {
		return ResponseBOM{}, fmt.Errorf("record not found: %d", input.ID)
	}
	r := obj.(*RowBOM)
	r.コード = input.コード
	r.版 = input.版
	r.名称 = input.名称
	r.UpdatedAt = now
	if _, err := tx.Update(r); err != nil {
		return ResponseBOM{}, err
	}

	if _, err := tx.Exec(`DELETE FROM "BOM明細" WHERE "BOM_ID"=$1`, input.ID); err != nil {
		return ResponseBOM{}, err
	}

	for _, l := range input.LinesBOM明細 {
		line := BOM明細{
			BOMID: input.ID,
			区分: l.区分,
			品目ID: l.品目ID,
			数量: l.数量,
			単位: l.単位,
			参照BOMコード: toNullString(l.参照BOMコード),
			参照BOM版: toNullString(l.参照BOM版),
			CreatedAt: now,
			UpdatedAt: now,
		}
		if err := tx.Insert(&line); err != nil {
			return ResponseBOM{}, err
		}
	}

	if err := tx.Commit(); err != nil {
		return ResponseBOM{}, err
	}
	return GetByIDSQLBOM(ctx, dbmap, input.ID)
}

func Execute削除SQLBOM(ctx context.Context, dbmap *gorp.DbMap, input 削除InputBOM) error {
	_, err := dbmap.WithContext(ctx).Delete(&RowBOM{Id: input.ID})
	return err
}

func Execute一括削除SQLBOM(ctx context.Context, dbmap *gorp.DbMap, input 一括削除InputBOM) error {
	if len(input.IDs) == 0 {
		return nil
	}
	ph := make([]string, len(input.IDs))
	args := make([]any, len(input.IDs))
	for i, id := range input.IDs {
		ph[i] = fmt.Sprintf("$%d", i+1)
		args[i] = id
	}
	_, err := dbmap.Db.ExecContext(ctx, fmt.Sprintf(`DELETE FROM "BOM" WHERE id IN (%s)`, strings.Join(ph, ",")), args...)
	return err
}

func GetByIDSQLBOM(ctx context.Context, dbmap *gorp.DbMap, id int) (ResponseBOM, error) {
	obj, err := dbmap.WithContext(ctx).Get(RowBOM{}, id)
	if err != nil {
		return ResponseBOM{}, err
	}
	if obj == nil {
		return ResponseBOM{}, fmt.Errorf("record not found: %d", id)
	}
	r := obj.(*RowBOM)
	return ResponseBOM{RowBOM: *r}, nil
}

func GetByIDBOM詳細SQL(ctx context.Context, dbmap *gorp.DbMap, id int) (ResponseBOM詳細, error) {
	bom, err := GetByIDSQLBOM(ctx, dbmap, id)
	if err != nil {
		return ResponseBOM詳細{}, err
	}

	rows, err := dbmap.Db.QueryContext(ctx,
		`SELECT bl.id, bl."BOM_ID", bl."区分", bl."品目ID", bl."数量", bl."単位", bl."参照BOMコード", bl."参照BOM版", bl.created_at, bl.updated_at, COALESCE(i."コード",''), COALESCE(i."名称",'') FROM "BOM明細" bl LEFT JOIN "品目" i ON bl."品目ID" = i.id WHERE bl."BOM_ID"=$1 ORDER BY bl.id`, id)
	if err != nil {
		return ResponseBOM詳細{}, err
	}
	defer rows.Close()

	var 製造品目アウトプット []BOM明細
	var 投入品目インプット []BOM明細
	for rows.Next() {
		var l BOM明細
		if err := rows.Scan(&l.Id, &l.BOMID, &l.区分, &l.品目ID, &l.数量, &l.単位, &l.参照BOMコード, &l.参照BOM版, &l.CreatedAt, &l.UpdatedAt, &l.品目コード, &l.品目名); err != nil {
			return ResponseBOM詳細{}, err
		}
		switch l.区分 {
		case 2:
			製造品目アウトプット = append(製造品目アウトプット, l)
		case 1:
			投入品目インプット = append(投入品目インプット, l)
		}
	}

	return ResponseBOM詳細{
		RowBOM: bom.RowBOM,
		製造品目アウトプット: 製造品目アウトプット,
		投入品目インプット: 投入品目インプット,
	}, nil
}

