// Code generated by gen-go.ts. DO NOT EDIT.
package features

import (
	"encoding/csv"
	"fmt"
	"net/http"
	"strconv"
	"time"
)

func (h *HandlerBOM) RegisterRoutesBOM(mux *http.ServeMux) {
	mux.HandleFunc("GET /BOM", h.HandlePageBOM)
	mux.HandleFunc("GET /BOM/new", h.HandleNewBOM)
	mux.HandleFunc("GET /BOM/{id}", h.HandleEditBOM)
	mux.HandleFunc("GET /api/BOM", h.Handle一覧BOM)
	mux.HandleFunc("GET /api/BOM/export", h.HandleExportBOM)
	mux.HandleFunc("POST /api/BOM", h.Handle登録BOM)
	mux.HandleFunc("DELETE /api/BOM", h.Handle一括削除BOM)
	mux.HandleFunc("PUT /api/BOM/{id}", h.Handle更新BOM)
	mux.HandleFunc("DELETE /api/BOM/{id}", h.Handle削除BOM)
	mux.HandleFunc("GET /api/BOM/line-row", h.HandleLineRowBOM)
}

func (h *HandlerBOM) HandlePageBOM(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderPageBOM().Render(r.Context(), w)
}

func (h *HandlerBOM) HandleNewBOM(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderNewPageBOM().Render(r.Context(), w)
}

func (h *HandlerBOM) HandleEditBOM(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	detail, err := h.GetByIDBOM詳細(r.Context(), id)
	if err != nil {
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderEditPageBOM(detail).Render(r.Context(), w)
}

func (h *HandlerBOM) Handle一覧BOM(w http.ResponseWriter, r *http.Request) {
	page, _ := strconv.Atoi(r.URL.Query().Get("page"))
	if page < 1 {
		page = 1
	}
	size, _ := strconv.Atoi(r.URL.Query().Get("size"))
	if size < 1 {
		size = 20
	}
	search := r.URL.Query().Get("q")
	result, err := h.Get一覧BOM(r.Context(), 一覧InputBOM{Page: page, Size: size, Search: search})
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderRowsBOM(result).Render(r.Context(), w)
}

func (h *HandlerBOM) Handle登録BOM(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	input := Parse作成FormBOM(r)
	result, err := h.Execute登録BOM(r.Context(), input)
	if err != nil {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusUnprocessableEntity)
		RenderErrorMessage(err.Error()).Render(r.Context(), w)
		return
	}
	w.Header().Set("HX-Redirect", fmt.Sprintf("/BOM/%d?saved=1", result.Id))
	w.WriteHeader(http.StatusNoContent)
}

func (h *HandlerBOM) Handle更新BOM(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	input := Parse更新FormBOM(r, id)
	_, err = h.Execute更新BOM(r.Context(), input)
	if err != nil {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusUnprocessableEntity)
		RenderErrorMessage(err.Error()).Render(r.Context(), w)
		return
	}
	w.Header().Set("HX-Redirect", fmt.Sprintf("/BOM/%d?saved=1", id))
	w.WriteHeader(http.StatusNoContent)
}

func (h *HandlerBOM) Handle削除BOM(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	if err := h.Execute削除BOM(r.Context(), 削除InputBOM{ID: id}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("HX-Redirect", "/BOM")
	w.WriteHeader(http.StatusNoContent)
}

func (h *HandlerBOM) Handle一括削除BOM(w http.ResponseWriter, r *http.Request) {
	form, err := ParseDeleteForm(r)
	if err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	ids := ParseIntSlice(form["ids[]"])
	if err := h.Execute一括削除BOM(r.Context(), 一括削除InputBOM{IDs: ids}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusOK)
}

func (h *HandlerBOM) HandleLineRowBOM(w http.ResponseWriter, r *http.Request) {
	section, _ := strconv.Atoi(r.URL.Query().Get("section"))
	rowKey := fmt.Sprintf("new-%d-%s", time.Now().UnixMilli(), r.URL.Query().Get("section"))
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderLineRowBOM(section, rowKey).Render(r.Context(), w)
}

func (h *HandlerBOM) HandleExportBOM(w http.ResponseWriter, r *http.Request) {
	format := r.URL.Query().Get("format")
	if format == "" {
		format = "csv"
	}
	search := r.URL.Query().Get("q")
	records, err := h.GetExportBOM(r.Context(), 一覧InputBOM{Search: search})
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	headers := []string{"BOMコード", "版", "名称"}
	rows := make([][]string, 0, len(records))
	for _, item := range records {
		rows = append(rows, []string{item.コード, item.版, item.名称})
	}
	suffix := time.Now().Format("20060102")
	if format == "xlsx" {
		WriteXLSX(w, "BOM_"+suffix+".xlsx", headers, rows)
		return
	}
	filename := "BOM_" + suffix
	mime := "text/csv;charset=utf-8"
	if format == "tsv" {
		mime = "text/tab-separated-values;charset=utf-8"
		filename += ".tsv"
	} else {
		filename += ".csv"
	}
	w.Header().Set("Content-Type", mime)
	w.Header().Set("Content-Disposition", "attachment; filename=\""+filename+"\"")
	w.Write([]byte{0xEF, 0xBB, 0xBF})
	cw := csv.NewWriter(w)
	if format == "tsv" {
		cw.Comma = '\t'
	}
	cw.Write(headers)
	for _, row := range rows {
		cw.Write(row)
	}
	cw.Flush()
}
