// Code generated by gen-dao. DO NOT EDIT.
package features

import (
	"database/sql"

	"github.com/go-gorp/gorp/v3"
)

// InitDbMap は gorp.DbMap を初期化し、全テーブルを登録する
func InitDbMap(db *sql.DB) *gorp.DbMap {
	dbmap := &gorp.DbMap{Db: db, Dialect: gorp.PostgresDialect{}}

	dbmap.AddTableWithName(RowBOM{}, "BOM").SetKeys(true, "Id")
	dbmap.AddTableWithName(BOM明細{}, "BOM明細").SetKeys(true, "Id")
	dbmap.AddTableWithName(Row取引{}, "取引").SetKeys(true, "Id")
	dbmap.AddTableWithName(Row取引区分{}, "取引区分").SetKeys(true, "Id")
	dbmap.AddTableWithName(Row品目{}, "品目").SetKeys(true, "Id")

	return dbmap
}
