// Code generated by gen-go.ts. DO NOT EDIT.
package features

import (
	"database/sql"
	"strconv"
)

// ParseIntSlice は文字列スライスを int スライスに変換する
func ParseIntSlice(ss []string) []int {
	result := make([]int, 0, len(ss))
	for _, s := range ss {
		if v, err := strconv.Atoi(s); err == nil {
			result = append(result, v)
		}
	}
	return result
}

// NullStrOr は sql.NullString が有効なら文字列を、無効なら fallback を返す
func NullStrOr(ns sql.NullString, fallback string) string {
	if ns.Valid {
		return ns.String
	}
	return fallback
}
