// Code generated by gen-go.ts. DO NOT EDIT.
package features

import (
	"database/sql"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"

	"github.com/xuri/excelize/v2"
)

var _ = fmt.Sprintf

// ParseDeleteForm は DELETE リクエストのボディをパースする。
// Go の ParseForm は DELETE メソッドのボディを読まないため手動でパースする。
func ParseDeleteForm(r *http.Request) (url.Values, error) {
	body, err := io.ReadAll(r.Body)
	if err != nil {
		return nil, err
	}
	defer r.Body.Close()
	return url.ParseQuery(string(body))
}

// ParseIntSlice は文字列スライスを int スライスに変換する
func ParseIntSlice(ss []string) []int {
	result := make([]int, 0, len(ss))
	for _, s := range ss {
		if v, err := strconv.Atoi(s); err == nil {
			result = append(result, v)
		}
	}
	return result
}

// NullStrOr は sql.NullString が有効なら文字列を、無効なら fallback を返す
func NullStrOr(ns sql.NullString, fallback string) string {
	if ns.Valid {
		return ns.String
	}
	return fallback
}

// toNullString は *string を sql.NullString に変換する
func toNullString(s *string) sql.NullString {
	if s == nil || *s == "" {
		return sql.NullString{}
	}
	return sql.NullString{String: *s, Valid: true}
}

// WriteXLSX はヘッダーと行データからXLSXを生成し、ResponseWriter に書き出す
func WriteXLSX(w http.ResponseWriter, filename string, headers []string, rows [][]string) error {
	f := excelize.NewFile()
	defer f.Close()
	sheet := "Sheet1"
	for i, h := range headers {
		cell, _ := excelize.CoordinatesToCellName(i+1, 1)
		f.SetCellValue(sheet, cell, h)
	}
	for r, row := range rows {
		for c, val := range row {
			cell, _ := excelize.CoordinatesToCellName(c+1, r+2)
			f.SetCellValue(sheet, cell, val)
		}
	}
	w.Header().Set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
	w.Header().Set("Content-Disposition", "attachment; filename*=UTF-8''"+url.PathEscape(filename))
	return f.Write(w)
}
