// Code generated by gen-go.ts. DO NOT EDIT.
package features

import (
	"net/http"
	"strconv"
)

func (h *Handler取引) RegisterRoutes取引(mux *http.ServeMux) {
	mux.HandleFunc("GET /取引", h.HandlePage取引)
	mux.HandleFunc("GET /api/取引", h.Handle一覧取引)
	mux.HandleFunc("POST /api/取引", h.Handle登録取引)
	mux.HandleFunc("DELETE /api/取引", h.Handle一括削除取引)
	mux.HandleFunc("PUT /api/取引/{id}", h.Handle更新取引)
	mux.HandleFunc("DELETE /api/取引/{id}", h.Handle削除取引)
	mux.HandleFunc("GET /api/取引/{id}/edit", h.HandleEdit取引)
}

func (h *Handler取引) HandlePage取引(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderPage取引().Render(r.Context(), w)
}

func (h *Handler取引) Handle一覧取引(w http.ResponseWriter, r *http.Request) {
	page, _ := strconv.Atoi(r.URL.Query().Get("page"))
	if page < 1 { page = 1 }
	size, _ := strconv.Atoi(r.URL.Query().Get("size"))
	if size < 1 { size = 20 }
	search := r.URL.Query().Get("q")
	result, err := h.Get一覧取引(r.Context(), 一覧Input取引{Page: page, Size: size, Search: search})
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderRows取引(result).Render(r.Context(), w)
}

func (h *Handler取引) Handle登録取引(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	input := Parse作成Form取引(r)
	_, err := h.Execute登録取引(r.Context(), input)
	if err != nil {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusUnprocessableEntity)
		RenderErrorMessage(err.Error()).Render(r.Context(), w)
		return
	}
	listResult, err := h.Get一覧取引(r.Context(), 一覧Input取引{Page: 1, Size: 20})
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("HX-Trigger", `{"show-toast": "登録しました"}`)
	RenderRows取引(listResult).Render(r.Context(), w)
}

func (h *Handler取引) Handle更新取引(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	input := Parse更新Form取引(r, id)
	result, err := h.Execute更新取引(r.Context(), input)
	if err != nil {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusUnprocessableEntity)
		RenderErrorMessage(err.Error()).Render(r.Context(), w)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("HX-Trigger", `{"show-toast": "更新しました"}`)
	RenderRow取引(result).Render(r.Context(), w)
}

func (h *Handler取引) Handle削除取引(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	if err := h.Execute削除取引(r.Context(), 削除Input取引{ID: id}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
}

func (h *Handler取引) Handle一括削除取引(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	ids := ParseIntSlice(r.Form["ids[]"])
	if err := h.Execute一括削除取引(r.Context(), 一括削除Input取引{IDs: ids}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusOK)
}

func (h *Handler取引) HandleEdit取引(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	item, err := h.GetByID取引(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderEditRow取引(item).Render(r.Context(), w)
}
