// Code generated by gen-dao. DO NOT EDIT.
package features

import (
	"context"
	"fmt"
	"math"
	"strings"
	"time"
	"github.com/go-gorp/gorp/v3"
)

var (
	_ = fmt.Sprintf
	_ = strings.Join
	_ = time.Now
	_ = math.Max
)

func Execute一覧SQL取引区分(ctx context.Context, dbmap *gorp.DbMap, input 一覧Input取引区分) (ListResult取引区分, error) {
	size := input.Size
	if size != 20 && size != 50 && size != 100 {
		size = 20
	}

	where := "WHERE 1=1"
	args := []any{}
	if input.Q != "" {
		args = append(args, "%"+input.Q+"%")
		idx := len(args)
		where += fmt.Sprintf(` AND ("コード" ILIKE $%d OR "名称" ILIKE $%d)`, idx, idx)
	}

	var total int
	if err := dbmap.SelectOne(&total, `SELECT COUNT(*) FROM "取引区分" `+where, args...); err != nil {
		return ListResult取引区分{}, err
	}

	totalPages := int(math.Max(1, math.Ceil(float64(total)/float64(size))))
	page := input.Page
	if page < 1 { page = 1 }
	if page > totalPages { page = totalPages }

	offset := len(args)
	rows, err := dbmap.Db.QueryContext(ctx,
		fmt.Sprintf(`SELECT id, "コード", "名称", "係数", created_at, updated_at FROM "取引区分" %s ORDER BY id DESC LIMIT $%d OFFSET $%d`, where, offset+1, offset+2),
		append(args, size, (page-1)*size)...)
	if err != nil {
		return ListResult取引区分{}, err
	}
	defer rows.Close()

	var records []Response取引区分
	for rows.Next() {
		var r Row取引区分
		if err := rows.Scan(&r.Id, &r.コード, &r.名称, &r.係数, &r.CreatedAt, &r.UpdatedAt); err != nil {
			return ListResult取引区分{}, err
		}
		records = append(records, Response取引区分{Row取引区分: r})
	}
	if records == nil { records = []Response取引区分{} }

	return ListResult取引区分{Records: records, CurrentPage: page, TotalPages: totalPages, PageSize: size}, nil
}

func Execute登録SQL取引区分(ctx context.Context, dbmap *gorp.DbMap, input 作成Input取引区分) (Response取引区分, error) {
	now := time.Now()
	r := Row取引区分{
		コード: input.コード,
		名称: input.名称,
		係数: input.係数,
		CreatedAt: now,
		UpdatedAt: now,
	}
	if err := dbmap.WithContext(ctx).Insert(&r); err != nil {
		return Response取引区分{}, err
	}
	return Response取引区分{Row取引区分: r}, nil
}

func Execute更新SQL取引区分(ctx context.Context, dbmap *gorp.DbMap, input 更新Input取引区分) (Response取引区分, error) {
	obj, err := dbmap.WithContext(ctx).Get(Row取引区分{}, input.ID)
	if err != nil {
		return Response取引区分{}, err
	}
	if obj == nil {
		return Response取引区分{}, fmt.Errorf("record not found: %d", input.ID)
	}
	r := obj.(*Row取引区分)
	r.コード = input.コード
	r.名称 = input.名称
	r.係数 = input.係数
	r.UpdatedAt = time.Now()
	if _, err := dbmap.WithContext(ctx).Update(r); err != nil {
		return Response取引区分{}, err
	}
	return Response取引区分{Row取引区分: *r}, nil
}

func Execute削除SQL取引区分(ctx context.Context, dbmap *gorp.DbMap, input 削除Input取引区分) error {
	_, err := dbmap.WithContext(ctx).Delete(&Row取引区分{Id: input.ID})
	return err
}

func Execute一括削除SQL取引区分(ctx context.Context, dbmap *gorp.DbMap, input 一括削除Input取引区分) error {
	if len(input.IDs) == 0 {
		return nil
	}
	ph := make([]string, len(input.IDs))
	args := make([]any, len(input.IDs))
	for i, id := range input.IDs {
		ph[i] = fmt.Sprintf("$%d", i+1)
		args[i] = id
	}
	_, err := dbmap.Db.ExecContext(ctx, fmt.Sprintf(`DELETE FROM "取引区分" WHERE id IN (%s)`, strings.Join(ph, ",")), args...)
	return err
}

func GetByIDSQL取引区分(ctx context.Context, dbmap *gorp.DbMap, id int) (Response取引区分, error) {
	obj, err := dbmap.WithContext(ctx).Get(Row取引区分{}, id)
	if err != nil {
		return Response取引区分{}, err
	}
	if obj == nil {
		return Response取引区分{}, fmt.Errorf("record not found: %d", id)
	}
	r := obj.(*Row取引区分)
	return Response取引区分{Row取引区分: *r}, nil
}

