// Code generated by gen-go.ts. DO NOT EDIT.
package features

import (
	"context"
	"database/sql"
)

type Handler取引区分 struct { DB *sql.DB }

func NewHandler取引区分(db *sql.DB) *Handler取引区分 {
	return &Handler取引区分{DB: db}
}

func (h *Handler取引区分) Get一覧取引区分(ctx context.Context, input 一覧Input取引区分) (ListResult取引区分, error) {
	return Execute一覧SQL取引区分(ctx, h.DB, input)
}

func (h *Handler取引区分) Execute登録取引区分(ctx context.Context, input 作成Input取引区分) (Response取引区分, error) {
	if err := Validate登録取引区分(ctx, h.DB, input); err != nil {
		return Response取引区分{}, err
	}
	return Execute登録SQL取引区分(ctx, h.DB, input)
}

func (h *Handler取引区分) Execute更新取引区分(ctx context.Context, input 更新Input取引区分) (Response取引区分, error) {
	if err := Validate更新取引区分(ctx, h.DB, input); err != nil {
		return Response取引区分{}, err
	}
	return Execute更新SQL取引区分(ctx, h.DB, input)
}

func (h *Handler取引区分) Execute削除取引区分(ctx context.Context, input 削除Input取引区分) error {
	return Execute削除SQL取引区分(ctx, h.DB, input)
}

func (h *Handler取引区分) Execute一括削除取引区分(ctx context.Context, input 一括削除Input取引区分) error {
	return Execute一括削除SQL取引区分(ctx, h.DB, input)
}

func (h *Handler取引区分) GetByID取引区分(ctx context.Context, id int) (Response取引区分, error) {
	return GetByIDSQL取引区分(ctx, h.DB, id)
}
