// Code generated by gen-go.ts. DO NOT EDIT.
package features

import (
	"context"
	"database/sql"
)

type Handler取引 struct{ DB *sql.DB }

func NewHandler取引(db *sql.DB) *Handler取引 {
	return &Handler取引{DB: db}
}

func (h *Handler取引) Get一覧取引(ctx context.Context, input 一覧Input取引) (ListResult取引, error) {
	return Execute一覧SQL取引(ctx, h.DB, input)
}

func (h *Handler取引) Execute登録取引(ctx context.Context, input 作成Input取引) (Response取引, error) {
	if err := Validate登録取引(ctx, h.DB, input); err != nil {
		return Response取引{}, err
	}
	return Execute登録SQL取引(ctx, h.DB, input)
}

func (h *Handler取引) Execute更新取引(ctx context.Context, input 更新Input取引) (Response取引, error) {
	if err := Validate更新取引(ctx, h.DB, input); err != nil {
		return Response取引{}, err
	}
	return Execute更新SQL取引(ctx, h.DB, input)
}

func (h *Handler取引) Execute削除取引(ctx context.Context, input 削除Input取引) error {
	return Execute削除SQL取引(ctx, h.DB, input)
}

func (h *Handler取引) Execute一括削除取引(ctx context.Context, input 一括削除Input取引) error {
	return Execute一括削除SQL取引(ctx, h.DB, input)
}

func (h *Handler取引) GetByID取引(ctx context.Context, id int) (Response取引, error) {
	return GetByIDSQL取引(ctx, h.DB, id)
}

func (h *Handler取引) GetExport取引(ctx context.Context, input 一覧Input取引) ([]Response取引, error) {
	return ExecuteExportSQL取引(ctx, h.DB, input)
}
