// Code generated by gen-dao. DO NOT EDIT.
package features

import (
	"context"
	"database/sql"
	"fmt"
	"math"
	"strings"
	"time"
)

var (
	_ = fmt.Sprintf
	_ = strings.Join
	_ = time.Now
	_ = math.Max
	_ sql.NullString
)

func Execute一覧SQL取引(ctx context.Context, db *sql.DB, input 一覧Input取引) (ListResult取引, error) {
	size := input.Size
	if size != 20 && size != 50 && size != 100 {
		size = 20
	}

	where := "WHERE 1=1"
	args := []any{}
	if input.開始日 != "" {
		args = append(args, input.開始日)
		where += fmt.Sprintf(` AND "日付" >= $%d`, len(args))
	}
	if input.終了日 != "" {
		args = append(args, input.終了日)
		where += fmt.Sprintf(` AND "日付" <= $%d`, len(args))
	}

	var total int
	if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM "取引" `+where, args...).Scan(&total); err != nil {
		return ListResult取引{}, err
	}

	totalPages := int(math.Max(1, math.Ceil(float64(total)/float64(size))))
	page := input.Page
	if page < 1 {
		page = 1
	}
	if page > totalPages {
		page = totalPages
	}

	offset := len(args)
	rows, err := db.QueryContext(ctx,
		fmt.Sprintf(`SELECT id, "日付", "取引区分ID", "品目ID", "単価", "数量", "金額", created_at, updated_at FROM "取引" %s ORDER BY id DESC LIMIT $%d OFFSET $%d`, where, offset+1, offset+2),
		append(args, size, (page-1)*size)...)
	if err != nil {
		return ListResult取引{}, err
	}
	defer rows.Close()

	var records []Response取引
	for rows.Next() {
		var r Row取引
		if err := rows.Scan(&r.Id, &r.日付, &r.取引区分ID, &r.品目ID, &r.単価, &r.数量, &r.金額, &r.CreatedAt, &r.UpdatedAt); err != nil {
			return ListResult取引{}, err
		}
		records = append(records, Response取引{Row取引: r})
	}
	if records == nil {
		records = []Response取引{}
	}

	return ListResult取引{Records: records, CurrentPage: page, TotalPages: totalPages, PageSize: size}, nil
}

func Execute登録SQL取引(ctx context.Context, db *sql.DB, input 作成Input取引) (Response取引, error) {
	now := time.Now()
	var r Row取引
	err := db.QueryRowContext(ctx,
		`INSERT INTO "取引" ("日付", "取引区分ID", "品目ID", "単価", "数量", "金額", created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, "日付", "取引区分ID", "品目ID", "単価", "数量", "金額", created_at, updated_at`,
		input.日付, input.取引区分ID, input.品目ID, input.単価, input.数量, input.金額, now, now,
	).Scan(&r.Id, &r.日付, &r.取引区分ID, &r.品目ID, &r.単価, &r.数量, &r.金額, &r.CreatedAt, &r.UpdatedAt)
	if err != nil {
		return Response取引{}, err
	}
	return Response取引{Row取引: r}, nil
}

func Execute更新SQL取引(ctx context.Context, db *sql.DB, input 更新Input取引) (Response取引, error) {
	now := time.Now()
	_, err := db.ExecContext(ctx,
		`UPDATE "取引" SET "日付"=$1, "取引区分ID"=$2, "品目ID"=$3, "単価"=$4, "数量"=$5, "金額"=$6, updated_at=$7 WHERE id=$8`,
		input.日付, input.取引区分ID, input.品目ID, input.単価, input.数量, input.金額, now, input.ID)
	if err != nil {
		return Response取引{}, err
	}
	return GetByIDSQL取引(ctx, db, input.ID)
}

func Execute削除SQL取引(ctx context.Context, db *sql.DB, input 削除Input取引) error {
	_, err := db.ExecContext(ctx, `DELETE FROM "取引" WHERE id=$1`, input.ID)
	return err
}

func Execute一括削除SQL取引(ctx context.Context, db *sql.DB, input 一括削除Input取引) error {
	if len(input.IDs) == 0 {
		return nil
	}
	ph := make([]string, len(input.IDs))
	args := make([]any, len(input.IDs))
	for i, id := range input.IDs {
		ph[i] = fmt.Sprintf("$%d", i+1)
		args[i] = id
	}
	_, err := db.ExecContext(ctx, fmt.Sprintf(`DELETE FROM "取引" WHERE id IN (%s)`, strings.Join(ph, ",")), args...)
	return err
}

func GetByIDSQL取引(ctx context.Context, db *sql.DB, id int) (Response取引, error) {
	var r Row取引
	err := db.QueryRowContext(ctx,
		`SELECT id, "日付", "取引区分ID", "品目ID", "単価", "数量", "金額", created_at, updated_at FROM "取引" WHERE id=$1`, id,
	).Scan(&r.Id, &r.日付, &r.取引区分ID, &r.品目ID, &r.単価, &r.数量, &r.金額, &r.CreatedAt, &r.UpdatedAt)
	if err != nil {
		return Response取引{}, err
	}
	return Response取引{Row取引: r}, nil
}
