// Code generated by gen-go.ts. DO NOT EDIT.
package features

import (
	"encoding/csv"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"time"
)

func (h *Handler取引区分) RegisterRoutes取引区分(mux *http.ServeMux) {
	mux.HandleFunc("GET /取引区分", h.HandlePage取引区分)
	mux.HandleFunc("GET /api/取引区分", h.Handle一覧取引区分)
	mux.HandleFunc("GET /api/取引区分/export", h.HandleExport取引区分)
	mux.HandleFunc("POST /api/取引区分", h.Handle登録取引区分)
	mux.HandleFunc("DELETE /api/取引区分", h.Handle一括削除取引区分)
	mux.HandleFunc("PUT /api/取引区分/{id}", h.Handle更新取引区分)
	mux.HandleFunc("DELETE /api/取引区分/{id}", h.Handle削除取引区分)
	mux.HandleFunc("GET /api/取引区分/{id}/edit", h.HandleEdit取引区分)
}

func (h *Handler取引区分) HandlePage取引区分(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderPage取引区分().Render(r.Context(), w)
}

func (h *Handler取引区分) Handle一覧取引区分(w http.ResponseWriter, r *http.Request) {
	page, _ := strconv.Atoi(r.URL.Query().Get("page"))
	if page < 1 {
		page = 1
	}
	size, _ := strconv.Atoi(r.URL.Query().Get("size"))
	if size < 1 {
		size = 20
	}
	qParam := r.URL.Query().Get("q")
	result, err := h.Get一覧取引区分(r.Context(), 一覧Input取引区分{Page: page, Size: size, Q: qParam})
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderRows取引区分(result).Render(r.Context(), w)
}

func (h *Handler取引区分) Handle登録取引区分(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	input := Parse作成Form取引区分(r)
	_, err := h.Execute登録取引区分(r.Context(), input)
	if err != nil {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusUnprocessableEntity)
		RenderErrorMessage(err.Error()).Render(r.Context(), w)
		return
	}
	listResult, err := h.Get一覧取引区分(r.Context(), 一覧Input取引区分{Page: 1, Size: 20})
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("HX-Trigger", `{"show-toast": "登録しました"}`)
	RenderRows取引区分(listResult).Render(r.Context(), w)
}

func (h *Handler取引区分) Handle更新取引区分(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	input := Parse更新Form取引区分(r, id)
	result, err := h.Execute更新取引区分(r.Context(), input)
	if err != nil {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusUnprocessableEntity)
		RenderErrorMessage(err.Error()).Render(r.Context(), w)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("HX-Trigger", `{"show-toast": "更新しました"}`)
	RenderRow取引区分(result).Render(r.Context(), w)
}

func (h *Handler取引区分) Handle削除取引区分(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	if err := h.Execute削除取引区分(r.Context(), 削除Input取引区分{ID: id}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
}

func (h *Handler取引区分) Handle一括削除取引区分(w http.ResponseWriter, r *http.Request) {
	form, err := ParseDeleteForm(r)
	if err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	ids := ParseIntSlice(form["ids[]"])
	if err := h.Execute一括削除取引区分(r.Context(), 一括削除Input取引区分{IDs: ids}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusOK)
}

func (h *Handler取引区分) HandleEdit取引区分(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	item, err := h.GetByID取引区分(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderEditRow取引区分(item).Render(r.Context(), w)
}

func (h *Handler取引区分) HandleExport取引区分(w http.ResponseWriter, r *http.Request) {
	format := r.URL.Query().Get("format")
	if format == "" {
		format = "csv"
	}
	qParam := r.URL.Query().Get("q")
	records, err := h.GetExport取引区分(r.Context(), 一覧Input取引区分{Q: qParam})
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	headers := []string{"取引区分コード", "取引区分名称", "受払係数"}
	rows := make([][]string, 0, len(records))
	for _, item := range records {
		rows = append(rows, []string{item.コード, item.名称, fmt.Sprintf("%d", item.係数)})
	}
	suffix := time.Now().Format("20060102")
	if format == "xlsx" {
		WriteXLSX(w, "取引区分_"+suffix+".xlsx", headers, rows)
		return
	}
	filename := "取引区分_" + suffix
	mime := "text/csv;charset=utf-8"
	if format == "tsv" {
		mime = "text/tab-separated-values;charset=utf-8"
		filename += ".tsv"
	} else {
		filename += ".csv"
	}
	w.Header().Set("Content-Type", mime)
	w.Header().Set("Content-Disposition", "attachment; filename*=UTF-8''"+url.PathEscape(filename))
	w.Write([]byte{0xEF, 0xBB, 0xBF})
	cw := csv.NewWriter(w)
	if format == "tsv" {
		cw.Comma = '\t'
	}
	cw.Write(headers)
	for _, row := range rows {
		cw.Write(row)
	}
	cw.Flush()
}
