// Code generated by gen-go.ts. DO NOT EDIT.
package features

import (
	"database/sql"
	"time"
)

// Row品目 は items テーブルの行
type Row品目 struct {
	Id int `db:"id"`
	Code string `db:"code"`
	Name string `db:"name"`
	Category sql.NullString `db:"category"`
	Price int `db:"price"`
	Barcode sql.NullString `db:"barcode"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type 作成Input品目 struct {
	Code string
	Name string
	Category *string
	Price int
	Barcode *string
}

type 更新Input品目 struct {
	ID int
	Code string
	Name string
	Category *string
	Price int
	Barcode *string
}

type 削除Input品目 struct { ID int }
type 一括削除Input品目 struct { IDs []int }
type 一覧Input品目 struct {
	Page int
	Size int
	Q string
	Category string
}

type Response品目 struct { Row品目 }

type ListResult品目 struct {
	Records     []Response品目
	CurrentPage int
	TotalPages  int
	PageSize    int
}
