// Code generated by gen-go.ts. DO NOT EDIT.
package features

import (
	"net/http"
	"strconv"
)

func (h *Handler品目) RegisterRoutes品目(mux *http.ServeMux) {
	mux.HandleFunc("GET /品目", h.HandlePage品目)
	mux.HandleFunc("GET /api/品目", h.Handle一覧品目)
	mux.HandleFunc("POST /api/品目", h.Handle登録品目)
	mux.HandleFunc("DELETE /api/品目", h.Handle一括削除品目)
	mux.HandleFunc("PUT /api/品目/{id}", h.Handle更新品目)
	mux.HandleFunc("DELETE /api/品目/{id}", h.Handle削除品目)
	mux.HandleFunc("GET /api/品目/{id}/edit", h.HandleEdit品目)
}

func (h *Handler品目) HandlePage品目(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderPage品目().Render(r.Context(), w)
}

func (h *Handler品目) Handle一覧品目(w http.ResponseWriter, r *http.Request) {
	page, _ := strconv.Atoi(r.URL.Query().Get("page"))
	if page < 1 { page = 1 }
	size, _ := strconv.Atoi(r.URL.Query().Get("size"))
	if size < 1 { size = 20 }
	qParam := r.URL.Query().Get("q")
	categoryParam := r.URL.Query().Get("category")
	result, err := h.Get一覧品目(r.Context(), 一覧Input品目{Page: page, Size: size, Q: qParam, Category: categoryParam})
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderRows品目(result).Render(r.Context(), w)
}

func (h *Handler品目) Handle登録品目(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	input := Parse作成Form品目(r)
	_, err := h.Execute登録品目(r.Context(), input)
	if err != nil {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusUnprocessableEntity)
		RenderErrorMessage(err.Error()).Render(r.Context(), w)
		return
	}
	listResult, err := h.Get一覧品目(r.Context(), 一覧Input品目{Page: 1, Size: 20})
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("HX-Trigger", `{"show-toast": "登録しました"}`)
	RenderRows品目(listResult).Render(r.Context(), w)
}

func (h *Handler品目) Handle更新品目(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	input := Parse更新Form品目(r, id)
	result, err := h.Execute更新品目(r.Context(), input)
	if err != nil {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusUnprocessableEntity)
		RenderErrorMessage(err.Error()).Render(r.Context(), w)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("HX-Trigger", `{"show-toast": "更新しました"}`)
	RenderRow品目(result).Render(r.Context(), w)
}

func (h *Handler品目) Handle削除品目(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	if err := h.Execute削除品目(r.Context(), 削除Input品目{ID: id}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
}

func (h *Handler品目) Handle一括削除品目(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request", http.StatusBadRequest)
		return
	}
	ids := ParseIntSlice(r.Form["ids[]"])
	if err := h.Execute一括削除品目(r.Context(), 一括削除Input品目{IDs: ids}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusOK)
}

func (h *Handler品目) HandleEdit品目(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}
	item, err := h.GetByID品目(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	RenderEditRow品目(item).Render(r.Context(), w)
}
