// cmd/gen-dao/main.go — _dao_gen.go + dbmap_gen.go を生成する
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"
)

// ── JSON config 型定義 ──

type Config struct {
	Entities []Entity `json:"entities"`
}

type Entity struct {
	Name                string   `json:"name"`
	Table               string   `json:"table"`
	RowStruct           string   `json:"rowStruct"`
	ResponseStruct      string   `json:"responseStruct"`
	ListResultStruct    string   `json:"listResultStruct"`
	CreateInput         string   `json:"createInput"`
	UpdateInput         string   `json:"updateInput"`
	DeleteInput         string   `json:"deleteInput"`
	BatchDeleteInput    string   `json:"batchDeleteInput"`
	ListInput           string   `json:"listInput"`
	CreateWithLines     string   `json:"createWithLinesInput"`
	UpdateWithLines     string   `json:"updateWithLinesInput"`
	Fields              []Field  `json:"fields"`
	Search              *Search  `json:"search"`
	Filters             []Filter `json:"filters"`
	Child               *Child   `json:"child"`
	Detail              *Detail  `json:"detail"`
}

type Field struct {
	Go        string `json:"go"`
	DB        string `json:"db"`
	Type      string `json:"type"`
	InputType string `json:"inputType"`
	PK        bool   `json:"pk"`
	Auto      bool   `json:"auto"`
	Timestamp bool   `json:"timestamp"`
	Nullable  bool   `json:"nullable"`
}

type Search struct {
	InputField string   `json:"inputField"`
	Columns    []string `json:"columns"`
}

type Filter struct {
	InputField string `json:"inputField"`
	Column     string `json:"column"`
	Op         string `json:"op"` // "ilike", "eq", "gte", "lte"
}

type Child struct {
	Struct      string       `json:"struct"`
	Table       string       `json:"table"`
	ParentFK    string       `json:"parentFK"`
	ParentFKGo  string       `json:"parentFKGo"`
	LinesField  string       `json:"linesField"`
	InputStruct string       `json:"inputStruct"`
	Fields      []Field      `json:"fields"`
	InputFields []ChildInput `json:"inputFields"`
}

type ChildInput struct {
	Go       string `json:"go"`
	Type     string `json:"type"`
	Nullable bool   `json:"nullable"`
}

type Detail struct {
	ResponseStruct string        `json:"responseStruct"`
	Joins          []Join        `json:"joins"`
	Discriminator  Discriminator `json:"discriminator"`
}

type Join struct {
	Table     string      `json:"table"`
	Alias     string      `json:"alias"`
	ChildCol  string      `json:"childCol"`
	ParentCol string      `json:"parentCol"`
	Fields    []JoinField `json:"fields"`
}

type JoinField struct {
	Column string `json:"column"`
	As     string `json:"as"`
}

type Discriminator struct {
	Field  string  `json:"field"`
	Groups []Group `json:"groups"`
}

type Group struct {
	Value         int    `json:"value"`
	ResponseField string `json:"responseField"`
}

// ── SQL クォート ──

func sqlQ(name string) string {
	for _, c := range name {
		if c > 127 || c == ' ' {
			return `"` + name + `"`
		}
	}
	// ASCII but uppercase or mixed → quote
	if strings.ContainsAny(name, "ABCDEFGHIJKLMNOPQRSTUVWXYZ ") {
		return `"` + name + `"`
	}
	return name
}

// ── メイン ──

func main() {
	configPath := "internal/features/dao_config.json"
	if len(os.Args) > 1 {
		configPath = os.Args[1]
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		log.Fatalf("config読み込み失敗: %v", err)
	}
	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		log.Fatalf("config parse失敗: %v", err)
	}

	for _, e := range cfg.Entities {
		var sb strings.Builder
		genHeader(&sb, e)
		genList(&sb, e)
		if e.Child != nil {
			genCreateWithLines(&sb, e)
			genUpdateWithLines(&sb, e)
		} else {
			genCreate(&sb, e)
			genUpdate(&sb, e)
		}
		genDelete(&sb, e)
		genBatchDelete(&sb, e)
		genGetByID(&sb, e)
		if e.Detail != nil {
			genDetail(&sb, e)
		}

		prefix := e.Name
		outPath := fmt.Sprintf("internal/features/%s_dao_gen.go", prefix)
		if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
			log.Fatalf("%s 書き込み失敗: %v", outPath, err)
		}
		fmt.Printf("generated %s\n", outPath)
	}

	// dbmap_gen.go
	genDbMap(cfg)
	fmt.Println("generated internal/features/dbmap_gen.go")
}

// ── ヘッダー ──

func genHeader(sb *strings.Builder, e Entity) {
	sb.WriteString("// Code generated by gen-dao. DO NOT EDIT.\n")
	sb.WriteString("package features\n\n")

	imports := []string{
		`"context"`,
		`"fmt"`,
		`"math"`,
		`"strings"`,
		`"time"`,
		`"github.com/go-gorp/gorp/v3"`,
	}

	sb.WriteString("import (\n")
	for _, imp := range imports {
		sb.WriteString("\t" + imp + "\n")
	}
	sb.WriteString(")\n\n")

	// suppress unused imports
	sb.WriteString("var (\n")
	sb.WriteString("\t_ = fmt.Sprintf\n")
	sb.WriteString("\t_ = strings.Join\n")
	sb.WriteString("\t_ = time.Now\n")
	sb.WriteString("\t_ = math.Max\n")
	sb.WriteString(")\n\n")
}

// ── 一覧 (List) ──

func genList(sb *strings.Builder, e Entity) {
	JP := e.Name
	table := sqlQ(e.Table)

	// SELECT columns
	var selCols []string
	for _, f := range e.Fields {
		selCols = append(selCols, sqlQ(f.DB))
	}
	selectList := strings.Join(selCols, ", ")

	// Scan args
	var scanArgs []string
	for _, f := range e.Fields {
		scanArgs = append(scanArgs, "&r."+f.Go)
	}
	scanList := strings.Join(scanArgs, ", ")

	sb.WriteString(fmt.Sprintf("func Execute一覧SQL%s(ctx context.Context, dbmap *gorp.DbMap, input %s) (%s, error) {\n", JP, e.ListInput, e.ListResultStruct))
	sb.WriteString("\tsize := input.Size\n")
	sb.WriteString("\tif size != 20 && size != 50 && size != 100 {\n\t\tsize = 20\n\t}\n\n")
	sb.WriteString(fmt.Sprintf("\twhere := \"WHERE 1=1\"\n"))
	sb.WriteString("\targs := []any{}\n")

	// search clause
	if e.Search != nil && len(e.Search.Columns) > 0 {
		sb.WriteString(fmt.Sprintf("\tif input.%s != \"\" {\n", e.Search.InputField))
		sb.WriteString(fmt.Sprintf("\t\targs = append(args, \"%%\"+input.%s+\"%%\")\n", e.Search.InputField))
		var clauses []string
		for _, col := range e.Search.Columns {
			clauses = append(clauses, fmt.Sprintf(`%s ILIKE $%%d`, sqlQ(col)))
		}
		sb.WriteString(fmt.Sprintf("\t\tidx := len(args)\n"))
		joined := strings.Join(clauses, " OR ")
		sb.WriteString(fmt.Sprintf("\t\twhere += fmt.Sprintf(` AND (%s)`, %s)\n",
			joined, repeatIdx(len(e.Search.Columns))))
		sb.WriteString("\t}\n")
	}

	// filter clauses
	for _, f := range e.Filters {
		sb.WriteString(fmt.Sprintf("\tif input.%s != \"\" {\n", f.InputField))
		switch f.Op {
		case "ilike":
			sb.WriteString(fmt.Sprintf("\t\targs = append(args, \"%%\"+input.%s+\"%%\")\n", f.InputField))
			sb.WriteString(fmt.Sprintf("\t\twhere += fmt.Sprintf(` AND %s ILIKE $%%d`, len(args))\n", sqlQ(f.Column)))
		case "eq":
			sb.WriteString(fmt.Sprintf("\t\targs = append(args, input.%s)\n", f.InputField))
			sb.WriteString(fmt.Sprintf("\t\twhere += fmt.Sprintf(` AND %s = $%%d`, len(args))\n", sqlQ(f.Column)))
		case "gte":
			sb.WriteString(fmt.Sprintf("\t\targs = append(args, input.%s)\n", f.InputField))
			sb.WriteString(fmt.Sprintf("\t\twhere += fmt.Sprintf(` AND %s >= $%%d`, len(args))\n", sqlQ(f.Column)))
		case "lte":
			sb.WriteString(fmt.Sprintf("\t\targs = append(args, input.%s)\n", f.InputField))
			sb.WriteString(fmt.Sprintf("\t\twhere += fmt.Sprintf(` AND %s <= $%%d`, len(args))\n", sqlQ(f.Column)))
		}
		sb.WriteString("\t}\n")
	}

	sb.WriteString("\n\tvar total int\n")
	sb.WriteString(fmt.Sprintf("\tif err := dbmap.SelectOne(&total, `SELECT COUNT(*) FROM %s `+where, args...); err != nil {\n", table))
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n\n", e.ListResultStruct))

	sb.WriteString("\ttotalPages := int(math.Max(1, math.Ceil(float64(total)/float64(size))))\n")
	sb.WriteString("\tpage := input.Page\n")
	sb.WriteString("\tif page < 1 { page = 1 }\n")
	sb.WriteString("\tif page > totalPages { page = totalPages }\n\n")

	sb.WriteString("\toffset := len(args)\n")
	sb.WriteString(fmt.Sprintf("\trows, err := dbmap.Db.QueryContext(ctx,\n"))
	sb.WriteString(fmt.Sprintf("\t\tfmt.Sprintf(`SELECT %s FROM %s %%s ORDER BY id DESC LIMIT $%%d OFFSET $%%d`, where, offset+1, offset+2),\n", selectList, table))
	sb.WriteString("\t\tappend(args, size, (page-1)*size)...)\n")
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", e.ListResultStruct))
	sb.WriteString("\tdefer rows.Close()\n\n")

	sb.WriteString(fmt.Sprintf("\tvar records []%s\n", e.ResponseStruct))
	sb.WriteString("\tfor rows.Next() {\n")
	sb.WriteString(fmt.Sprintf("\t\tvar r %s\n", e.RowStruct))
	sb.WriteString(fmt.Sprintf("\t\tif err := rows.Scan(%s); err != nil {\n", scanList))
	sb.WriteString(fmt.Sprintf("\t\t\treturn %s{}, err\n\t\t}\n", e.ListResultStruct))
	sb.WriteString(fmt.Sprintf("\t\trecords = append(records, %s{%s: r})\n", e.ResponseStruct, e.RowStruct))
	sb.WriteString("\t}\n")
	sb.WriteString(fmt.Sprintf("\tif records == nil { records = []%s{} }\n\n", e.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\treturn %s{Records: records, CurrentPage: page, TotalPages: totalPages, PageSize: size}, nil\n", e.ListResultStruct))
	sb.WriteString("}\n\n")
}

// repeatIdx generates "idx, idx, idx..." for N search columns
func repeatIdx(n int) string {
	parts := make([]string, n)
	for i := range parts {
		parts[i] = "idx"
	}
	return strings.Join(parts, ", ")
}

// ── 登録 (Create) — 単純CRUD ──

func genCreate(sb *strings.Builder, e Entity) {
	JP := e.Name

	sb.WriteString(fmt.Sprintf("func Execute登録SQL%s(ctx context.Context, dbmap *gorp.DbMap, input %s) (%s, error) {\n", JP, e.CreateInput, e.ResponseStruct))
	sb.WriteString("\tnow := time.Now()\n")
	sb.WriteString(fmt.Sprintf("\tr := %s{\n", e.RowStruct))
	for _, f := range e.Fields {
		if f.PK && f.Auto {
			continue
		}
		if f.Timestamp {
			sb.WriteString(fmt.Sprintf("\t\t%s: now,\n", f.Go))
			continue
		}
		if f.Nullable {
			sb.WriteString(fmt.Sprintf("\t\t%s: toNullString(input.%s),\n", f.Go, f.Go))
		} else {
			sb.WriteString(fmt.Sprintf("\t\t%s: input.%s,\n", f.Go, f.Go))
		}
	}
	sb.WriteString("\t}\n")
	sb.WriteString("\tif err := dbmap.WithContext(ctx).Insert(&r); err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", e.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\treturn %s{%s: r}, nil\n", e.ResponseStruct, e.RowStruct))
	sb.WriteString("}\n\n")
}

// ── 更新 (Update) — 単純CRUD ──

func genUpdate(sb *strings.Builder, e Entity) {
	JP := e.Name

	sb.WriteString(fmt.Sprintf("func Execute更新SQL%s(ctx context.Context, dbmap *gorp.DbMap, input %s) (%s, error) {\n", JP, e.UpdateInput, e.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\tobj, err := dbmap.WithContext(ctx).Get(%s{}, input.ID)\n", e.RowStruct))
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", e.ResponseStruct))
	sb.WriteString("\tif obj == nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, fmt.Errorf(\"record not found: %%d\", input.ID)\n\t}\n", e.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\tr := obj.(*%s)\n", e.RowStruct))
	for _, f := range e.Fields {
		if f.PK || f.Timestamp {
			continue
		}
		if f.Nullable {
			sb.WriteString(fmt.Sprintf("\tr.%s = toNullString(input.%s)\n", f.Go, f.Go))
		} else {
			sb.WriteString(fmt.Sprintf("\tr.%s = input.%s\n", f.Go, f.Go))
		}
	}
	sb.WriteString("\tr.UpdatedAt = time.Now()\n")
	sb.WriteString("\tif _, err := dbmap.WithContext(ctx).Update(r); err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", e.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\treturn %s{%s: *r}, nil\n", e.ResponseStruct, e.RowStruct))
	sb.WriteString("}\n\n")
}

// ── 登録 with Lines (Header-Body) ──

func genCreateWithLines(sb *strings.Builder, e Entity) {
	JP := e.Name
	ch := e.Child

	sb.WriteString(fmt.Sprintf("func Execute登録SQL%s(ctx context.Context, dbmap *gorp.DbMap, input %s) (%s, error) {\n", JP, e.CreateWithLines, e.ResponseStruct))
	sb.WriteString("\tnow := time.Now()\n")
	sb.WriteString("\ttx, err := dbmap.Begin()\n")
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", e.ResponseStruct))
	sb.WriteString("\tdefer tx.Rollback()\n\n")

	// Insert parent
	sb.WriteString(fmt.Sprintf("\tr := %s{\n", e.RowStruct))
	for _, f := range e.Fields {
		if f.PK && f.Auto {
			continue
		}
		if f.Timestamp {
			sb.WriteString(fmt.Sprintf("\t\t%s: now,\n", f.Go))
			continue
		}
		if f.Nullable {
			sb.WriteString(fmt.Sprintf("\t\t%s: toNullString(input.%s),\n", f.Go, f.Go))
		} else {
			sb.WriteString(fmt.Sprintf("\t\t%s: input.%s,\n", f.Go, f.Go))
		}
	}
	sb.WriteString("\t}\n")
	sb.WriteString("\tif err := tx.Insert(&r); err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n\n", e.ResponseStruct))

	// Insert child lines
	sb.WriteString(fmt.Sprintf("\tfor _, l := range input.%s {\n", ch.LinesField))
	sb.WriteString(fmt.Sprintf("\t\tline := %s{\n", ch.Struct))
	sb.WriteString(fmt.Sprintf("\t\t\t%s: r.Id,\n", ch.ParentFKGo))
	for _, cf := range ch.InputFields {
		if cf.Nullable {
			sb.WriteString(fmt.Sprintf("\t\t\t%s: toNullString(l.%s),\n", cf.Go, cf.Go))
		} else {
			sb.WriteString(fmt.Sprintf("\t\t\t%s: l.%s,\n", cf.Go, cf.Go))
		}
	}
	sb.WriteString("\t\t\tCreatedAt: now,\n")
	sb.WriteString("\t\t\tUpdatedAt: now,\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t\tif err := tx.Insert(&line); err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\t\treturn %s{}, err\n\t\t}\n", e.ResponseStruct))
	sb.WriteString("\t}\n\n")

	sb.WriteString("\tif err := tx.Commit(); err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", e.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\treturn %s{%s: r}, nil\n", e.ResponseStruct, e.RowStruct))
	sb.WriteString("}\n\n")
}

// ── 更新 with Lines (Header-Body) ──

func genUpdateWithLines(sb *strings.Builder, e Entity) {
	JP := e.Name
	ch := e.Child
	childTable := sqlQ(ch.Table)
	childFK := sqlQ(ch.ParentFK)

	sb.WriteString(fmt.Sprintf("func Execute更新SQL%s(ctx context.Context, dbmap *gorp.DbMap, input %s) (%s, error) {\n", JP, e.UpdateWithLines, e.ResponseStruct))
	sb.WriteString("\tnow := time.Now()\n")
	sb.WriteString("\ttx, err := dbmap.Begin()\n")
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", e.ResponseStruct))
	sb.WriteString("\tdefer tx.Rollback()\n\n")

	// Fetch and update parent
	sb.WriteString(fmt.Sprintf("\tobj, err := tx.Get(%s{}, input.ID)\n", e.RowStruct))
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", e.ResponseStruct))
	sb.WriteString("\tif obj == nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, fmt.Errorf(\"record not found: %%d\", input.ID)\n\t}\n", e.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\tr := obj.(*%s)\n", e.RowStruct))
	for _, f := range e.Fields {
		if f.PK || f.Timestamp {
			continue
		}
		if f.Nullable {
			sb.WriteString(fmt.Sprintf("\tr.%s = toNullString(input.%s)\n", f.Go, f.Go))
		} else {
			sb.WriteString(fmt.Sprintf("\tr.%s = input.%s\n", f.Go, f.Go))
		}
	}
	sb.WriteString("\tr.UpdatedAt = now\n")
	sb.WriteString("\tif _, err := tx.Update(r); err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n\n", e.ResponseStruct))

	// Delete old lines and re-insert
	sb.WriteString(fmt.Sprintf("\tif _, err := tx.Exec(`DELETE FROM %s WHERE %s=$1`, input.ID); err != nil {\n", childTable, childFK))
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n\n", e.ResponseStruct))

	sb.WriteString(fmt.Sprintf("\tfor _, l := range input.%s {\n", ch.LinesField))
	sb.WriteString(fmt.Sprintf("\t\tline := %s{\n", ch.Struct))
	sb.WriteString(fmt.Sprintf("\t\t\t%s: input.ID,\n", ch.ParentFKGo))
	for _, cf := range ch.InputFields {
		if cf.Nullable {
			sb.WriteString(fmt.Sprintf("\t\t\t%s: toNullString(l.%s),\n", cf.Go, cf.Go))
		} else {
			sb.WriteString(fmt.Sprintf("\t\t\t%s: l.%s,\n", cf.Go, cf.Go))
		}
	}
	sb.WriteString("\t\t\tCreatedAt: now,\n")
	sb.WriteString("\t\t\tUpdatedAt: now,\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t\tif err := tx.Insert(&line); err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\t\treturn %s{}, err\n\t\t}\n", e.ResponseStruct))
	sb.WriteString("\t}\n\n")

	sb.WriteString("\tif err := tx.Commit(); err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", e.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\treturn GetByIDSQL%s(ctx, dbmap, input.ID)\n", JP))
	sb.WriteString("}\n\n")
}

// ── 削除 (Delete) ──

func genDelete(sb *strings.Builder, e Entity) {
	JP := e.Name
	sb.WriteString(fmt.Sprintf("func Execute削除SQL%s(ctx context.Context, dbmap *gorp.DbMap, input %s) error {\n", JP, e.DeleteInput))
	sb.WriteString(fmt.Sprintf("\t_, err := dbmap.WithContext(ctx).Delete(&%s{Id: input.ID})\n", e.RowStruct))
	sb.WriteString("\treturn err\n")
	sb.WriteString("}\n\n")
}

// ── 一括削除 (Batch Delete) ──

func genBatchDelete(sb *strings.Builder, e Entity) {
	JP := e.Name
	table := sqlQ(e.Table)

	sb.WriteString(fmt.Sprintf("func Execute一括削除SQL%s(ctx context.Context, dbmap *gorp.DbMap, input %s) error {\n", JP, e.BatchDeleteInput))
	sb.WriteString("\tif len(input.IDs) == 0 {\n\t\treturn nil\n\t}\n")
	sb.WriteString("\tph := make([]string, len(input.IDs))\n")
	sb.WriteString("\targs := make([]any, len(input.IDs))\n")
	sb.WriteString("\tfor i, id := range input.IDs {\n")
	sb.WriteString("\t\tph[i] = fmt.Sprintf(\"$%d\", i+1)\n")
	sb.WriteString("\t\targs[i] = id\n")
	sb.WriteString("\t}\n")
	sb.WriteString(fmt.Sprintf("\t_, err := dbmap.Db.ExecContext(ctx, fmt.Sprintf(`DELETE FROM %s WHERE id IN (%%s)`, strings.Join(ph, \",\")), args...)\n", table))
	sb.WriteString("\treturn err\n")
	sb.WriteString("}\n\n")
}

// ── GetByID ──

func genGetByID(sb *strings.Builder, e Entity) {
	JP := e.Name

	sb.WriteString(fmt.Sprintf("func GetByIDSQL%s(ctx context.Context, dbmap *gorp.DbMap, id int) (%s, error) {\n", JP, e.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\tobj, err := dbmap.WithContext(ctx).Get(%s{}, id)\n", e.RowStruct))
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", e.ResponseStruct))
	sb.WriteString("\tif obj == nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, fmt.Errorf(\"record not found: %%d\", id)\n\t}\n", e.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\tr := obj.(*%s)\n", e.RowStruct))
	sb.WriteString(fmt.Sprintf("\treturn %s{%s: *r}, nil\n", e.ResponseStruct, e.RowStruct))
	sb.WriteString("}\n\n")
}

// ── Detail (BOM詳細) ──

func genDetail(sb *strings.Builder, e Entity) {
	JP := e.Name
	d := e.Detail
	ch := e.Child

	sb.WriteString(fmt.Sprintf("func GetByID%s詳細SQL(ctx context.Context, dbmap *gorp.DbMap, id int) (%s, error) {\n", JP, d.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\tbom, err := GetByIDSQL%s(ctx, dbmap, id)\n", JP))
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n\n", d.ResponseStruct))

	// Build JOIN query
	// SELECT child columns + join columns
	var selCols []string
	for _, f := range ch.Fields {
		selCols = append(selCols, "bl."+sqlQ(f.DB))
	}
	for _, j := range d.Joins {
		for _, jf := range j.Fields {
			selCols = append(selCols, fmt.Sprintf("COALESCE(%s.%s,'')", j.Alias, sqlQ(jf.Column)))
		}
	}
	selectList := strings.Join(selCols, ", ")

	// JOIN clause
	var joinClauses []string
	for _, j := range d.Joins {
		joinClauses = append(joinClauses,
			fmt.Sprintf("LEFT JOIN %s %s ON bl.%s = %s.%s",
				sqlQ(j.Table), j.Alias, sqlQ(j.ChildCol), j.Alias, sqlQ(j.ParentCol)))
	}
	joinSQL := strings.Join(joinClauses, " ")

	childTable := sqlQ(ch.Table)
	childFK := sqlQ(ch.ParentFK)

	sb.WriteString(fmt.Sprintf("\trows, err := dbmap.Db.QueryContext(ctx,\n"))
	sb.WriteString(fmt.Sprintf("\t\t`SELECT %s FROM %s bl %s WHERE bl.%s=$1 ORDER BY bl.id`, id)\n",
		selectList, childTable, joinSQL, childFK))
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n\t}\n", d.ResponseStruct))
	sb.WriteString("\tdefer rows.Close()\n\n")

	// Scan columns
	var scanArgs []string
	for _, f := range ch.Fields {
		scanArgs = append(scanArgs, "&l."+f.Go)
	}
	for _, j := range d.Joins {
		for _, jf := range j.Fields {
			scanArgs = append(scanArgs, "&l."+jf.As)
		}
	}
	scanList := strings.Join(scanArgs, ", ")

	// Declare group slices
	for _, g := range d.Discriminator.Groups {
		sb.WriteString(fmt.Sprintf("\tvar %s []%s\n", g.ResponseField, ch.Struct))
	}

	sb.WriteString("\tfor rows.Next() {\n")
	sb.WriteString(fmt.Sprintf("\t\tvar l %s\n", ch.Struct))
	sb.WriteString(fmt.Sprintf("\t\tif err := rows.Scan(%s); err != nil {\n", scanList))
	sb.WriteString(fmt.Sprintf("\t\t\treturn %s{}, err\n\t\t}\n", d.ResponseStruct))

	// Discriminator switch
	sb.WriteString(fmt.Sprintf("\t\tswitch l.%s {\n", d.Discriminator.Field))
	for _, g := range d.Discriminator.Groups {
		sb.WriteString(fmt.Sprintf("\t\tcase %d:\n", g.Value))
		sb.WriteString(fmt.Sprintf("\t\t\t%s = append(%s, l)\n", g.ResponseField, g.ResponseField))
	}
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t}\n\n")

	// Return
	sb.WriteString(fmt.Sprintf("\treturn %s{\n", d.ResponseStruct))
	sb.WriteString(fmt.Sprintf("\t\t%s: bom.%s,\n", e.RowStruct, e.RowStruct))
	for _, g := range d.Discriminator.Groups {
		sb.WriteString(fmt.Sprintf("\t\t%s: %s,\n", g.ResponseField, g.ResponseField))
	}
	sb.WriteString("\t}, nil\n")
	sb.WriteString("}\n\n")
}

// ── dbmap_gen.go ──

func genDbMap(cfg Config) {
	var sb strings.Builder
	sb.WriteString("// Code generated by gen-dao. DO NOT EDIT.\n")
	sb.WriteString("package features\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"database/sql\"\n\n")
	sb.WriteString("\t\"github.com/go-gorp/gorp/v3\"\n")
	sb.WriteString(")\n\n")
	sb.WriteString("// InitDbMap は gorp.DbMap を初期化し、全テーブルを登録する\n")
	sb.WriteString("func InitDbMap(db *sql.DB) *gorp.DbMap {\n")
	sb.WriteString("\tdbmap := &gorp.DbMap{Db: db, Dialect: gorp.PostgresDialect{}}\n\n")

	for _, e := range cfg.Entities {
		sb.WriteString(fmt.Sprintf("\tdbmap.AddTableWithName(%s{}, %q).SetKeys(true, \"Id\")\n", e.RowStruct, e.Table))
		if e.Child != nil {
			sb.WriteString(fmt.Sprintf("\tdbmap.AddTableWithName(%s{}, %q).SetKeys(true, \"Id\")\n", e.Child.Struct, e.Child.Table))
		}
	}

	sb.WriteString("\n\treturn dbmap\n")
	sb.WriteString("}\n")

	if err := os.WriteFile("internal/features/dbmap_gen.go", []byte(sb.String()), 0644); err != nil {
		log.Fatalf("dbmap_gen.go 書き込み失敗: %v", err)
	}
}
